apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-system-backend
  labels:
    app: ticket-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-system
  template:
    metadata:
      labels:
        app: ticket-system
    spec:
      containers:
      - name: ticket-system-app
        image: ticket-system-backend:0.0.2-SNAPSHOT
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/ticket-system"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "1234"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-system-service
  labels:
    app: ticket-system
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: ticket-system
